service: auto-cleanup-web

custom:
  log_level: INFO # DEBUG for dev | INFO for prod
  region: ${opt:region, "ap-southeast-2"} # AWS deployment region
  client:
    bucketName: reaper.strongdm.rocks
    distributionFolder: ./src
    sse: AES256

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, "prod"} # overwrite via CLI "--stage dev"
  region: ${self:custom.region}
  profile: ${opt:profile, ""} # overwrite via CLI "--aws-profile saml"

package:
  individually: true
  exclude:
    - node_modules/**

resources:
  Resources:
    WebBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: reaper.strongdm.rocks
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

plugins:
  - serverless-finch
